name = "PDFSandwich"
uuid = "78c8a9bf-03de-4425-87c3-987af89136f6"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
